import Link from "next/link"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <>
      <header className="bg-sky-950 p-2">
        <Link href="/">
          <img
            src="https://www.mlbstatic.com/team-logos/league-on-dark/1.svg"
            className="h-24"
            alt="mlb logo"
          ></img>
        </Link>
      </header>
      <div className="m-4">{children}</div>
    </>
  )
}
