import Link from "next/link"
import "./globals.css"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-sky-950 p-2">
          <Link href="/">
            <img
              src="https://www.mlbstatic.com/team-logos/league-on-dark/1.svg"
              className="h-24"
              alt="mlb logo"
            ></img>
          </Link>
        </header>
        {children}
      </body>
    </html>
  )
}
